version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: six8/pyinstaller-alpine:alpine-v3.4-pyinstaller-develop

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      # disable due to https://github.com/squaremo/kubeyaml/issues/8
      #    make test

      - run: make

      - deploy:
          name: Maybe push master image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker tag "quay.io/brezerk/kubeyaml" \
                         "quay.io/brezerk/kubeyaml:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
              docker push "quay.io/brezerk/kubeyaml:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
            fi

      - deploy:
          name: Maybe push release image
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq "^[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" quay.io
              docker tag quay.io/brezerk/kubeyaml "quay.io/brezerk/kubeyaml:${CIRCLE_TAG}"
              docker push "quay.io/brezerk/kubeyaml:${CIRCLE_TAG}"
            fi

workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-[a-z]+)?/
